### ISSUE TITLE
Build Initial Test Cases

### ISSUE THREAD

**Issue by joshuahannan** [TrueBitFoundation/interactive-coin-offerings#15]
## What is it?

We need someone to build out an initial set of tests for the Interactive Crowdsale.

### Problem

Right now, we are fairly confident with the library but we need tests to ensure that it behaves as intended.  Once this initial simple run through of basic functionality is completed, others can then copy the tests and make new versions that test different possible situations in the sale.

### Solution

Write a set of tests to ensure basic functionality in the token sale Library.

### Steps to implement

Pre-sale
- [x] Tests to ensure sale is initialized correctly. 
- [x] Doesn't accept bids
During the Sale, Pre-Withdrawal Lock
- [x] Test basic bids and withdrawals
- [x] Make sure the valuation pointer is moving correctly across the buckets
- [x] Make sure bids are reflected in contribution amount and total Valuations
- [ ] Ensure the withdrawal penalty is applied correctly
- [ ] Ensure that bids with minimal valuations get full refunds
During the Sale, Post-Withdrawal Lock
- [x] Ensure bidders can't withdraw bids
- [x] Test basic bids and pointer movement.  The valuation increases.
Post-Sale
- [ ] Write post-sale tests to ensure the correct amount of tokens are available to withdraw, bids with personal valuations under the total valuation get full refunds, and bids with accurate personal valuations get tokens.

**Comment by Hackdom** [comment]
This should be checked and closed after issues #18, #20, #21, and #22
