### ISSUE TITLE
Update README to better describe the implementation

### ISSUE THREAD

**Issue by joshuahannan** [TrueBitFoundation/interactive-coin-offerings#16]
## What is it?

README needs to be an easy to understand description of the function of the protocol

### Problem

The README adequately describes the protocol implementation, but could use some touching up to better help with understanding for people not already familiar with the code

### Solution

Rewrite/add sections to the README to help with understanding

### Steps to implement

- [ ] Talk with @Hackdom  or @joshuahannan about what confuses you about the documentation
- [ ] Make suggestions/PRs with potential fixes to the documentation

**Comment by Hackdom** [comment]
@joshuahannan I thought I saw this updated, did you?

**Comment by joshuahannan** [comment]
I updated it but I wanted to get people's feedback before we close the issue. I also need to finish the diagrams
