### ISSUE TITLE
Setup Testing Environment 

### ISSUE THREAD

**Issue by Hackdom** [TrueBitFoundation/interactive-coin-offerings#19]
## What is it?

We need to properly setup a testrpc environment for the crowdsale that includes a lot of accounts with sufficient amounts of Ether

### Problem

We do not have a common test environment 

### Solution

Submit a script that gives everyone a good test environment 

### Steps to implement

- [ ] Build a script to have a good testrpc environment 
- [ ] Push to the repo and notify

**Comment by gustavoguimaraes** [comment]
I can do this.
