### ISSUE TITLE
Test Token Withdrawals

### ISSUE THREAD

**Issue by Hackdom** [TrueBitFoundation/interactive-coin-offerings#20]
## What is it?

After issue #19

Tokens will be withdrawn after the sale is over. Anyone with a bid submitted using a personal cap at or above the current sale value is eligible to withdraw tokens after the sale is over. 

Those with personal caps above the current value should have all of their bid accepted and only tokens available for withdraw. The number of tokens should be calculated accurately.

Those with personal caps at the valuation will have their bid split between accepted eth for tokens and leftover eth not available. This calculation needs to be tested for accuracy.

Any bids with personal caps below the valuation would not be accepted and no tokens can be withdrawn, all ether in the bid should be available for withdraw.

**Comment by joshuahannan** [comment]
as soon as we get in the tests for accepting bids, I'll start working on this
