### ISSUE TITLE
Test Eth Withdrawals

### ISSUE THREAD

**Issue by Hackdom** [TrueBitFoundation/interactive-coin-offerings#21]
## What is it?

After issue #19

During the sale, bids are available for withdraw prior to the withdrawal lock. Depending on the time of the bid, and time of withdrawal, a penalty should be enforced for any withdrawals. The penalty amount kept should be committed to the sale and the rest should be returned upon a withdraw request. The calculation of this penalty should be accurate. 

After the withdrawal lock is in place, no bid withdrawals should be allowed until the valuation pointer moves above the personal cap. That is, the valuation pointer can only move up after the withdrawal lock and, as it moves up with new bids committed, bids with personal caps below the value should be made available for withdrawal because they are no longer eligible and bids with caps above the pointer should be committed and not eligible for withdrawal.

**Comment by gustavoguimaraes** [comment]
I believe I am able to take this one.
