### ISSUE TITLE
don't commit `node_modules` to git

### ISSUE THREAD

**Issue by Shrugs** [TrueBitFoundation/interactive-coin-offerings#24]
## What is it?

We shouldn't commit node modules to git.

### Problem

Node modules are committed to git.

### Solution

Remove the node_modules folder from git and use gitignore to avoid including them int he future.

### Steps to implement

`git rm -rf --cached node_modules`

A recommended `.gitignore` is provided below:

```
#####=== Node ===#####

# Logs
logs
*.log

# Runtime data
pids
*.pid
*.seed

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# Dependency directory
node_modules

# Debug log from npm
npm-debug.log
```

**Comment by gustavoguimaraes** [comment]
I believe the `build/` folder does not to be committed either.

**Comment by Hackdom** [comment]
The only thing with ignoring the build folder is it drops the library artifacts. We use the libraries for the intended purpose of deploy once and use everywhere. All of the libraries are deployed on the networks with addresses stored in the artifact. The only actual deployment that has to occur is the contract.

**Comment by gustavoguimaraes** [comment]
I see your point @Hackdom. However each time someone migrates the contracts in development mode it will change the `build` folder.  A better approach is to create a config file with a JSon as such:

```
{
  Ethereum: {
    address: {
      Library: '0x859e7E76cAeDe3b642FC84862809f60c055cb731',
      AnotherLibrary: '0x1e2F058C43ac8965938F6e9CA286685A3E63F24E',
    }
  }
}
```


and access it as:

```
const config = require('../node_modules/config') // using the config library here
const LibraryAddress = config.get('Ethereum.address.Library')

const Library = artifacts.require('./Library.sol')
const library = LIbrary.at(LibraryAddress)

```

Anyways, I added the `build` folder in my commit as this issue only refers to node_modules folder.

**Comment by Hackdom** [comment]
That’s great information, is this sort of thing documented somewhere or is it a flow you’ve adopted?

**Comment by gustavoguimaraes** [comment]
Something I adopted.

**Comment by Hackdom** [comment]
Movin
