### ISSUE TITLE
Expand Test Cases

### ISSUE THREAD

**Issue by joshuahannan** [TrueBitFoundation/interactive-coin-offerings#6]
There is an initial set of test cases that proved the base functionality, but they need to be expanded on to cover as many use cases as possible.  Common security issues need to be audited and tested for.

Speak to me if you want to assist with this and I can help explain how we are testing the library

**Comment by JGcarv** [comment]
Hello @joshuahannan , I'm interested! I think that writing tests is a great way to help and simultaneously get a hang of how everything works.

**Comment by joshuahannan** [comment]
awesome! Thanks for volunteering! I'll message you on Slack and we can work together to set up a test specification that we can put on here

**Comment by gustavoguimaraes** [comment]
I am interested in adding tests to the codebase.

**Comment by joshuahannan** [comment]
Moving this issue to a new thread: https://github.com/TrueBitFoundation/interactive-coin-offerings/issues/15
