### ISSUE TITLE
compiler error on undeclared identifier

### ISSUE THREAD

**Issue by maurelian** [TrueBitFoundation/interactive-coin-offerings#8]
The `_currtime` varaiables are undeclared.

```
$ truffle test
Using network 'test'.

Compiling ./contracts/Array256Lib.sol...
Compiling ./contracts/BasicMathLib.sol...
Compiling ./contracts/CrowdsaleLib.sol...
Compiling ./contracts/CrowdsaleToken.sol...
Compiling ./contracts/InteractiveCrowdsaleLib.sol...
Compiling ./contracts/InteractiveCrowdsaleTestContract.sol...
Compiling ./contracts/LinkedListLib.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/TestCrowdsaleLib.sol...
Compiling ./contracts/TestInteractiveCrowdsaleLib.sol...
Compiling ./contracts/TimeInteractiveCrowdsaleTestContract.sol...
Compiling ./contracts/TokenLib.sol...

/Users/primary/Projects/interactive-coin-offerings/InteractiveCrowdsale/truffle/contracts/InteractiveCrowdsaleLib.sol:194:9: DeclarationError: Undeclared identifier.
    if (_currtime >= self.endWithdrawlTime) {
        ^-------^
,/Users/primary/Projects/interactive-coin-offerings/InteractiveCrowdsale/truffle/contracts/InteractiveCrowdsaleLib.sol:277:17: DeclarationError: Undeclared identifier.
            if (_currtime >= self.endWithdrawlTime) {
                ^-------^
Compiliation failed. See above.
```

$ truffle version
Truffle v4.0.0-beta.0 (core: 4.0.0-beta.0)
Solidity v0.4.15 (solc-js)

**Comment by joshuahannan** [comment]
sorry about that. Must have missed it when I committed.  We are actually doing a complete redesign of the code to get rid of all the looping in the auto bid removal so I would hold off on doing too much with it right now.

**Comment by maurelian** [comment]
Great that you're using async/await for tests, much more readable. 

Truffle doesn't support `now` in solidity?

**Comment by joshuahannan** [comment]
Ah I wasn't very clear.  It does support now in solidity, but when we're testing, there isn't a way to override the now keyword so that we can run tests that depend on time calculations.  But I think we found a way to get around that

**Comment by maurelian** [comment]
Right, in case it's not what you're already using, you should be able to use testrpc's `evm_increasetime` function to move head in time.

I've heard good things about tempo: https://medium.com/@Digix/digix-dev-tool-release-tempo-f78d03aaae4e
